# EP0
a = [
  "episodes/global/animations/ctanlee/ctanlee-angry.json"
  "episodes/global/animations/ctanlee/ctanlee-idle.json"
  "episodes/global/animations/ctanlee/ctanlee-look-down.json"
  "episodes/global/animations/ctanlee/ctanlee-look-left.json"
  "episodes/global/animations/ctanlee/ctanlee-look-right.json"
  "episodes/global/animations/ctanlee/ctanlee-surprise.json"
  "episodes/global/animations/ctanlee/ctanlee-unhappy.json"
  "episodes/global/sounds/Intro_Credits.mp3"
  "episodes/episode0/sounds/SFX_Defender_Door_Open.mp3"
  "episodes/episode0/animations/splitdoor.json"
  "episodes/episode0/sounds/SFX_SoundTestButton.mp3"
  "episodes/global/sounds/MU_Ambient_Facility_no_notes.mp3"
  "episodes/episode0/animations/commandline.json"
  "episodes/episode0/sounds/Story_1_Warcore_1.mp3"
  "episodes/episode0/sounds/Story_1_Warcore_2.mp3"
  "episodes/episode0/animations/quarantine.json"
  "episodes/episode0/sounds/Story_1_Warcore_3.mp3"
  "episodes/episode0/sounds/Story_1_Warcore_4.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_1.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_2.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_4.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_7.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_8.mp3"
  "episodes/episode0/animations/powergrid1.json"
  "episodes/episode0/sounds/Story_1_Ctanlee_9.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_10.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_11.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_12.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_12b1.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_12b2.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_12c.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_12d.mp3"
  "episodes/episode0/sounds/SFX_Sektimus_Fleet_Impacts.mp3"
  "episodes/episode0/sounds/CIN_Intro_Sektimus.mp3"
  "episodes/episode0/animations/sektimus_pngs.json"
  "episodes/episode0/sounds/Story_1_Ctanlee_12e.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_16.mp3"
  "episodes/episode0/sounds/SFX_Crater.mp3"
  "episodes/episode0/animations/smoke1.json"
  "episodes/episode0/sounds/Story_1_Ctanlee_17.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_18a.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_18b.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_19.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_19b1.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_19b2.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_21.mp3"
  "episodes/episode0/sounds/Story_1_Dialogue_Panicking.mp3"
  "episodes/episode0/sounds/Story_1_Dialogue_Puke.mp3"
  "episodes/episode0/sounds/Story_1_Dialogue_Spirit.mp3"
  "episodes/episode0/animations/chip.json"
  "episodes/episode0/sounds/Story_1_Ctanlee_20.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_22.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_24.mp3"
  "episodes/episode0/sounds/Story_1_Ctanlee_25.mp3"
  "episodes/global/sounds/SFX_Level_Cadet.mp3"
  "episodes/global/animations/cadet.json"
]

# EP1 CH1
b = [
  "episodes/episode1/animations/c1-background-clouds-loop.json"
  "episodes/episode1/animations/c1_background_buildin.json"
  "episodes/episode1/sounds/Story_2_Ctanlee_X43.mp3"
  "episodes/episode1/sounds/Story_2_Ctanlee_1.mp3"
  "episodes/episode1/sounds/Story_2_Ctanlee_2.mp3"
  "episodes/episode1/sounds/Story_2_Ctanlee_3.mp3"
  "episodes/episode1/animations/substation_facility_build.json"
  "episodes/episode1/animations/substation_facility_loop.json"
  "episodes/episode1/sounds/SFX_FacilityType_Substation.mp3"
  "episodes/episode1/animations/generation_facility_build.json"
  "episodes/episode1/animations/generation_facility_loop.json"
  "episodes/episode1/sounds/SFX_FacilityType_GenerationPlant.mp3"
  "episodes/episode1/animations/control_facility_build.json"
  "episodes/episode1/animations/control_facility_loop.json"
  "episodes/episode1/sounds/SFX_FacilityType_ControlCenter.mp3"
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode1/animations/interior_build.json"
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode1/sounds/Story_2_Ctanlee_4.mp3"
  "episodes/episode1/animations/asset_view.json"
  "episodes/episode1/animations/asset_bca_pca_label.json"
  "episodes/episode1/animations/asset_network_connections.json"
  "episodes/episode1/animations/asset_bcsi_label.json"
  "episodes/episode1/sounds/Story_2_Ctanlee_31.mp3"
  "episodes/episode1/sounds/Story_2_Ctanlee_32.mp3"
  "episodes/episode1/sounds/Story_2_Ctanlee_33.mp3"
]


# EP 2 CH1
c = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode1/animations/c1-background-clouds-loop.json"
  "episodes/episode1/animations/c1_background_buildin.json"
  "episodes/episode1/animations/interior_build.json"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode2/sounds/CIN_RobotMovement.mp3"
  "episodes/global/sounds/SFX_AttackSlamdown_KettleHead.mp3"
  "episodes/episode2/sounds/CIN_PhysicalAttack_DoorOpen.mp3"
  "episodes/episode2/sounds/CIN_PhysicalAttack_Screams.mp3"
  "episodes/episode2/sounds/CIN_RipServerFromWall.mp3"
  "episodes/episode2/sounds/CIN_PhysicalAttack_ServerCrash.mp3"
  "episodes/episode2/animations/kettle_attack_pngs.json"
  "episodes/episode2/sounds/Story_3_Ctanlee_1.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_2.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_3.mp3"
  "episodes/episode2/animations/perimeter_door_server.json"
  "episodes/episode2/sounds/Story_3_Ctanlee_4.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_5.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_6.mp3"
  "episodes/episode2/animations/card_scanner_build.json"
  "episodes/episode2/animations/card_scanner_pass.json"
  "episodes/episode2/sounds/SFX_PhysicalAccessControlSystem_TheCardGuardXT.mp3"
  "episodes/episode2/animations/hal_scanner_build.json"
  "episodes/episode2/animations/hal_scanner_pass.json"
  "episodes/episode2/sounds/SFX_PhysicalAccessControlSystem_HAL9000EyeScanner.mp3"
  "episodes/episode2/animations/kraken_scanner_build.json"
  "episodes/episode2/animations/kraken_scanner_pass.json"
  "episodes/episode2/sounds/SFX_PhysicalAccessControlSystem_WateryGraveKrakenSensor.mp3"
  "episodes/episode2/animations/perimeter_physical.json"
  "episodes/episode2/sounds/Story_3_Ctanlee_7.mp3"
  "episodes/episode2/sounds/CIN_RobotMovement.mp3"
  "episodes/episode2/sounds/CIN_PhysicalDefense_Klaxon.mp3"
  "episodes/episode2/sounds/CIN_PhysicalDefense_Laser.mp3"
  "episodes/episode2/sounds/CIN_PhysicalDefense_BlastedRobot.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_8a.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_8b.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_9.mp3"
  "episodes/episode2/sounds/Story_3_Ctanlee_15.mp3"
]

# EP3
d = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode1/animations/c1-background-clouds-loop.json"
  "episodes/episode1/animations/c1_background_buildin.json"
  "episodes/episode1/animations/interior_build.json"
  "episodes/global/sounds/MU_Attack_Music.mp3"
   "episodes/episode3/sounds/CIN_TreeMoving.mp3"
  "episodes/episode3/sounds/CIN_RobotTossing.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
   "episodes/episode3/sounds/CIN_TreeMoving.mp3"
  "episodes/global/sounds/SFX_AttackSlamdown_FlashBot.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/2001_Space.mp3"
  "episodes/episode3/sounds/CIN_TransmisionLinesBurning.mp3"
  "episodes/episode3/animations/kettle_bush_attack.json"
  "episodes/episode3/sounds/Story_4_Ctanlee_1.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_2.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_3.mp3"
  "episodes/global/animations/perimeter_ports.json"
  "episodes/episode3/sounds/Story_4_Ctanlee_4.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_5.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_6.mp3"
  "episodes/episode3/animations/duct_tape_build.json"
  "episodes/episode3/animations/duct_tape_install.json"
  "episodes/episode3/animations/duct_tape_defend.json"
  "episodes/episode3/sounds/SFX_PhysicalPortSecurity_DuctTape.mp3"
  "episodes/episode3/animations/kragle_build.json"
  "episodes/episode3/animations/kragle_install.json"
  "episodes/episode3/animations/kragle_defend.json"
  "episodes/episode3/sounds/SFX_PhysicalPortSecurity_TheKragle.mp3"
  "episodes/episode3/animations/umpire_build.json"
  "episodes/episode3/animations/umpire_install.json"
  "episodes/episode3/animations/umpire_defend.json"
  "episodes/episode3/sounds/SFX_PhysicalPortSecurity_PortUmpie.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_7.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_8.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode3/sounds/CIN_FlashDriveRejection.mp3"
  "episodes/episode3/sounds/CIN_HumanTossing.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_10.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_11.mp3"
]

# EP4 CH1
e = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode1/animations/c1-background-clouds-loop.json"
  "episodes/episode1/animations/c1_background_buildin.json"
  "episodes/episode1/animations/interior_build.json"
  "episodes/global/animations/perimeter_e5_physical.json"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode4/sounds/CIN_HumanExcited.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_HumanExcited.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_DoorOpen.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_DoorOpen.mp3"
  "episodes/global/sounds/SFX_AttackSlamdown_UnsavoryHuman.mp3"
  "episodes/episode4/sounds/CIN_RobotsMovingExplosion.mp3"
  "episodes/episode4/animations/5_defender_access_fail.json"
  "episodes/episode4/sounds/Story_5_Ctanlee_1.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_2.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_3.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_4.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_3.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_6.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_7.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_8.mp3"
  "episodes/episode4/animations/background_probe_build.json"
  "episodes/episode4/animations/background_probe_pass_a.json"
  "episodes/episode4/animations/background_probe_pass_b.json"
  "episodes/episode4/animations/background_probe_pass_c.json"
  "episodes/episode4/sounds/SFX_AccessControlSystem_BackgroundProbe.mp3"
  "episodes/episode4/animations/risk_detector_build.json"
  "episodes/episode4/animations/risk_detector_pass_a.json"
  "episodes/episode4/animations/risk_detector_pass_b.json"
  "episodes/episode4/animations/risk_detector_pass_c.json"
  "episodes/episode4/sounds/SFX_AccessControlSystem_RiskDetector.mp3"
  "episodes/episode4/animations/voight_kampff_build.json"
  "episodes/episode4/animations/voight_kampff_pass_a.json"
  "episodes/episode4/animations/voight_kampff_pass_b.json"
  "episodes/episode4/animations/voight_kampff_pass_c.json"
  "episodes/episode4/sounds/SFX_AccessControlSystem_VoightKampfDetector.mp3"
  "episodes/episode4/sounds/CIN_HumanExcited.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_DoorOpen.mp3"
  "episodes/episode4/sounds/CIN_Typing.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_9.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_10.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_11.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_ScannerShock.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_12.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_13.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_Typing.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_DoorOpen.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_Typing.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_14.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_15_alt.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_16.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_17.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_18.mp3"
]

# EP5 CH1

f = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode1/animations/c1-background-clouds-loop.json"
  "episodes/episode1/animations/c1_background_buildin.json"
  "episodes/episode1/animations/interior_build.json"
  "episodes/episode5/sounds/CIN_PersonSneaking.mp3"
  "episodes/episode5/animations/e5_skittering.json"
]

# EP3 CH2

g = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode3/animations/workstation_pointers.json"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode3/sounds/CIN_Quarantine.mp3"
  "episodes/episode3/animations/fatline_e41.json"
  "episodes/episode3/sounds/Story_4_Ctanlee_12.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_13.mp3"
  "episodes/episode3/sounds/Story_4_Warcore_1.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_1a.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_1b.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_1c.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_14.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_2a.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_2b.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_2c.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_3a.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_3b.mp3"
  "episodes/episode3/sounds/Story_4_Sektimus_3c.mp3"
  "episodes/episode3/animations/fatline_e42.json"
  "episodes/episode3/sounds/Story_4_Sektimus_4.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_15.mp3"
]

# EP3 CH3

h = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_TypingComputerCrash.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_VehicleRunning.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/global/sounds/SFX_AttackSlamdown_MimeBot.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_VehicleRunning.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_AssetConnection.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_HumanExcited.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_ComputerDialOut.mp3"
  "episodes/episode3/sounds/CIN_RobotHacking.mp3"
  "episodes/episode3/animations/change_assets_fail.json"
  "episodes/episode3/sounds/Story_4_Ctanlee_19.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_20.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_21.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_22.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_ThrowAwayComputer.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_TreeMoving.mp3"
  "episodes/episode3/sounds/CIN_RobotGetComputer.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_RobotHacking.mp3"
  "episodes/episode3/animations/change_assets_fail_part_2.json"
  "episodes/episode3/sounds/Story_4_Ctanlee_23.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_24.mp3"
  "episodes/episode3/animations/workstation_assets_1.json"
  "episodes/episode3/animations/workstation_assets_2.json"
  "episodes/global/animations/perimeter_change.json"
  "episodes/episode3/sounds/Story_4_Ctanlee_25.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_26.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_27.mp3"
  "episodes/episode3/animations/double_deuce_build.json"
  "episodes/episode3/animations/double_deuce_pass.json"
  "episodes/episode3/sounds/SFX_AssetChangeTools_DoubleDeuce.mp3"
  "episodes/episode3/animations/mr_fusion_build.json"
  "episodes/episode3/animations/mr_fusion_pass.json"
  "episodes/episode3/sounds/SFX_AssetChangeTools_MyFusion.mp3"
  "episodes/episode3/animations/dematerializer_build.json"
  "episodes/episode3/animations/dematerializer_pass.json"
  "episodes/episode3/sounds/SFX_AssetChangeTools_The De-Materializer.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_VehicleRunning.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_HumanTossing.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_AssetConnection.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/CIN_ThrowAwayComputer.mp3"
  "episodes/episode3/sounds/CIN_HumanWalking.mp3"
  "episodes/episode3/sounds/CIN_DoorOpen.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_28.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_29.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_30.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_31.mp3"
  "episodes/episode3/sounds/Story_4_Ctanlee_32.mp3"
  "episodes/global/sounds/SFX_Level_CyberCadet.mp3"
  "episodes/global/animations/cyber_cadet.json"
]

# EP4 CH2

i = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/episode4/sounds/CIN_Typing.mp3"
  "episodes/global/animations/user_account_1.json"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode4/sounds/CIN_Typing.mp3"
  "episodes/episode4/sounds/CIN_AccessGranted.mp3"
  "episodes/episode4/animations/5_user_account_fail.json"
  "episodes/episode4/sounds/Story_5_Ctanlee_19.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_20.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode4/sounds/CIN_Typing.mp3"
  "episodes/episode4/animations/5_user_account_pass.json"
  "episodes/episode4/sounds/Story_5_Ctanlee_21.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_22.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_23.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode3/sounds/CIN_Quarantine.mp3"
  "episodes/episode4/animations/intercept_e5_1.json"
  "episodes/episode4/sounds/Story_5_Warcore_1.mp3"
  "episodes/episode4/sounds/Story_5_Sektimus_1.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_24.mp3"
  "episodes/episode4/sounds/Story_5_Sektimus_2a.mp3"
  "episodes/episode4/sounds/Story_5_Sektimus_2b.mp3"
  "episodes/episode4/sounds/Story_5_Sektimus_2c.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_25.mp3"
  "episodes/episode4/sounds/Story_5_Sektimus_3.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_26a.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_26b.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_26c.mp3"
  "episodes/episode4/animations/intercept_e5_2.json"
  "episodes/episode4/sounds/Story_5_Sektimus_4.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_27.mp3"
]


# EP4 CH3

j = [
  "episodes/global/sounds/MU_Ambient_Facility.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/global/sounds/SFX_AttackSlamdown_AuditBot.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_BlackOutGrid.mp3"
  "episodes/episode4/animations/5_auditbot_fail.json"
  "episodes/episode4/sounds/Story_5_Ctanlee_28.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_29.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_30.mp3"
  "episodes/global/animations/perimeter_door.json"
  "episodes/episode4/sounds/Story_5_Ctanlee_31.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_32.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_33.mp3"
  "episodes/episode4/animations/log_book_build.json"
  "episodes/episode4/animations/log_book_pass.json"
  "episodes/episode4/sounds/SFX_VisitorEscortSystem_GuestLogBook.mp3"
  "episodes/episode4/animations/escort_leash_build.json"
  "episodes/episode4/animations/escort_leash_pass.json"
  "episodes/episode4/sounds/SFX_VisitorEscortSystem_EscortLeash.mp3"
  "episodes/episode4/animations/tractor_beam_build.json"
  "episodes/episode4/animations/tractor_beam_pass.json"
  "episodes/episode4/sounds/SFX_VisitorEscortSystem_VisitorTractorBeam.mp3"
  "episodes/global/sounds/MU_Attack_Music.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/CIN_DoorOpen.mp3"
  "episodes/episode4/sounds/CIN_HumanWalking.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_34.mp3"
  "episodes/episode4/sounds/Story_5_Ctanlee_35.mp3"
  "episodes/global/sounds/SFX_Level_MasterCadet.mp3"
  "episodes/global/animations/master_cadet.json"
]

prepManifest = (ar, manifest)->
  for item in ar
    if /.mp3|.m4a/.test(item)
      manifest.push {src:item,  id:item}


createjs.Sound.alternateExtensions = ["mp3", "m4a"]
preloadQueue = new createjs.LoadQueue()
preloadQueue.installPlugin createjs.Sound

$loader = $ ".load"
# On load progress
progressHandler = preloadQueue.on "progress", (e)=>
  $loader.css width:"#{e.loaded*100}%"

# On load complete
completeHandler = preloadQueue.on "complete", ()=>
  $loader.css background: "#1078cd"


manifest = []
prepManifest a, manifest
prepManifest b, manifest
prepManifest c, manifest
prepManifest d, manifest
prepManifest e, manifest
prepManifest f, manifest
prepManifest g, manifest
prepManifest h, manifest
prepManifest i, manifest
prepManifest j, manifest

# Load it!
preloadQueue.loadManifest manifest